config/routes.rb
Rails.application.routes.draw do
  get 'rock_paper_scissors/index'

  root "games#index"

  resources :secret_numbers, :only => [:new, :show]
  resources :rock_paper_scissors, :only => [:new, :show]

  get '/games', to: 'games#index'
  get '/secret_numbers', to: 'secret_numbers#new'
  get '/rock_paper_scissors', to: 'rock_paper_scissors#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
end

app/controllers/rock_paper_scissors_controller.rb
class RockPaperScissorsController < ApplicationController
  helper_method :win
  def index

  end
  def show
    @RHS = rand(3)
    @LHS = params[:id].to_i
  end
  def win
    @judge = false
    if @LHS == 0 && @RHS == 2 then @judge = true end
    if @LHS == 1 && @RHS == 0 then @judge = true end
    if @LHS == 2 && @RHS == 1 then @judge = true end
    @judge
  end
end

app/controllers/secret_numbers_controller.rb
class SecretNumbersController < ApplicationController
  def new
  end

  def show
    # get a random number from 1-10
    @secret_number = rand(5)+1

    # get the user chosen number from params
    # the param is named 'id' because of route convention
    # lastly, we want to turn it from a String to an Integer
    # that way, we can compare it to the secret number (which is an int)
    @chosen_number = params[:id].to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rock_paper_scissors_helper.rb
module RockPaperScissorsHelper
end

app/views/games/index.html.erb
<h1>Welcome to the Game Center!</h1>

<p>Choose a game below to get started:</p>

<br/>

<table>
  <tr>
    <td>
      <%=link_to image_tag("games/secret-number.jpg"), new_secret_number_path %>
      <h4>SECRET NUMBER</h4>
    </td>
    <td>
      <%=link_to image_tag("games/rock-paper-scissors.jpg"), rock_paper_scissors_path %>
      <h4>Rock Paper Scissors</h4>
    </td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Games on Rails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Built with love by Salman Ansari, BEWD Instructor in Sep 2013 -->
  <!-- Upgraded to Rails 4.1 by Hubert Lee, BEWD Instructor in Nov 2014 -->
</head>
<body>
  <% unless controller.controller_name == 'games' %>
    <%= link_to '< Back to Game Center', '/' %>
  <% end %>

  <div id="content">
    <%= yield %>
  </div>
</body>
</html>

app/views/rock_paper_scissors/index.html.erb
<h1>Welcome to RockPaperScissors</h1>

<p>To play this game, all you need to know is <b>ROCK PAPER and SCISSORS</b>.</p>

<p>Choose carefully... you only get one try!</p>

<br/>

<h2>Pick a throw:<h2>

<% (0..2).each do |throw| %>
  <%= link_to image_tag("rock_paper_scissors/#{throw}.jpeg"), rock_paper_scissor_path(throw) %>
<% end %>

app/views/rock_paper_scissors/show.html.erb
<h1><% if win %>
<%=    "You win" %>
<% elsif @LHS == @RHS %>
<%=    "DRAW" %>
<% else %>
<%=    "You lose" %>
<% end %> </h1>
<h1></h1>




<%= image_tag("rock_paper_scissors/#{@LHS}.jpeg") %>

<%= image_tag("rock_paper_scissors/#{@RHS}flip.jpeg") %>

app/views/secret_numbers/new.html.erb
<h1>Welcome to Secret Number!</h1>

<p>To play this game, all you have to do is guess a number. If you guess the <u>secret number</u>, you win!</p>

<p>Choose carefully... you only get one try!</p>

<br/>

<h2>Pick a number:<h2>

<% (1..5).each do |number| %>
  <%= link_to image_tag("secret_numbers/#{number}.jpeg"), secret_number_path(number) %>
<% end %>

app/views/secret_numbers/show.html.erb
<% if @secret_number == @chosen_number %>
  <h1>CONGRATS! YOU WON!</h1>
  <h4>The secret number was <%=@secret_number%></h4>
  <p><%= image_tag 'games/cat-wins.gif' %></p>
<% else %>
  <h1>Sorry, you lose...</h1>
  <h4>The secret number was <%=@secret_number%></h4>
  <p><%= image_tag 'games/loser.gif' %></p>
<% end %>

<p>
  <h3><%= link_to "PLAY AGAIN", new_secret_number_path %></h3>
</p>